

GET http://localhost:1234/api/usersController/getUserById/325004034


###
GET http://localhost:1234/api/usersController/logIn/325004034/pob2534

###
GET http://localhost:1234/api/usersController/doesExists/325004054
###

POST http://localhost:1234/api/usersController/addNewUser HTTP/1.1
Content-Type: application/json

{
  "id": "011959830",
  "password": "8520",
  "firstName": "Shira",
  "lastName": "Levi",
  "email":"hhh" ,
  "phone": "0587480452",
  "dateOfBirth": "2000-12-04T00:00:00.000Z"
}

###
DELETE http://localhost:1234/api/usersController/deleteUser/011959830

###
PATCH http://localhost:1234/api/usersController/updateUser/011959830 
Content-Type: application/json

{
  "id": "011959830",
  "password": "8520",
  "firstName": "Shira",
  "lastName": "Levi",
  "email":"" ,
  "phone": "0587480452",
  "dateOfBirth": "2000-12-04T00:00:00.000Z"
}
###
GET  http://localhost:1234/api/machinesController/getAllMachines
###
GET  http://localhost:1234/api/machinesController/getAllMachines
###
GET http://localhost:1234/api/machinesController/getMachineById/15
###

DELETE http://localhost:1234/api/machinesController/deleteMachine/14

###

GET  http://localhost:1234/api/workoutscontroller/getAllWorkouts
###
GET  http://localhost:1234/api/workoutsController/getworkoutById/1

###
DELETE http://localhost:1234/api/workoutsController/deleteworkout/1
###

GET http://localhost:1234/api/machinesController/getMachinesByWorkoutGoal/1

###
POST http://localhost:1234/api/machinesController/addNewMachine HTTP/1.1
Content-Type: application/json

{
  "name": "2מכשיר נוסף",
  "pic": "2מכשיר נוסף.jpg",
  "numUnits": 10,
  "maxAge": 120,
  "maxWeight": 230
}

###
GET http://localhost:1234/api/workoutsController/getWorksoutrByUserId/212907737
###

PATCH http://localhost:1234/api/workoutsController/updateWorkout/2
Content-Type: application/json


{
    "id": 2,
    "date": "2012-01-01T00:00:00.000Z",
    "time": "2012-01-01T00:00:00.000Z",
    "diffacalty": 2,
    "workoutLength": 20,
    "userId": "212907737"
  

}